// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxpjeiujVJszMrVBevj-VDcU49THOhTGs',
    appId: '1:169127693044:web:50b3f4a07fc3deadb6eca1',
    messagingSenderId: '169127693044',
    projectId: 'my-project-baws',
    authDomain: 'my-project-baws.firebaseapp.com',
    storageBucket: 'my-project-baws.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCseuccEZsZhlesVhRkg8B5sNxe_taP3B0',
    appId: '1:169127693044:android:7eeae60570b49064b6eca1',
    messagingSenderId: '169127693044',
    projectId: 'my-project-baws',
    storageBucket: 'my-project-baws.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwCR1kL4IzI5AGyOk4-ZOnc6nL-pd30Fs',
    appId: '1:169127693044:ios:fe98969b06ae2881b6eca1',
    messagingSenderId: '169127693044',
    projectId: 'my-project-baws',
    storageBucket: 'my-project-baws.appspot.com',
    iosBundleId: 'com.example.myProjectBaws',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwCR1kL4IzI5AGyOk4-ZOnc6nL-pd30Fs',
    appId: '1:169127693044:ios:fe98969b06ae2881b6eca1',
    messagingSenderId: '169127693044',
    projectId: 'my-project-baws',
    storageBucket: 'my-project-baws.appspot.com',
    iosBundleId: 'com.example.myProjectBaws',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxpjeiujVJszMrVBevj-VDcU49THOhTGs',
    appId: '1:169127693044:web:54df06f0233f161db6eca1',
    messagingSenderId: '169127693044',
    projectId: 'my-project-baws',
    authDomain: 'my-project-baws.firebaseapp.com',
    storageBucket: 'my-project-baws.appspot.com',
  );
}
